version: "3.8"
services:
  ip_check:
    container_name: ip_check
    image: ghcr.io/2boom-ua/ip_check:latest
    network_mode: "host"
    volumes:
      - ./config.json:/ip_check/config.json
    environment:
      - TZ=UTC
    restart: always

